language: python
cache: pip
python:
- 3.7.8
- 3.8
- 3.9
env:
  global:
  - PYTHONPATH=.:vendor
install:
- pip install -r tests/requirements.txt
- cp packaging/setup.py .
- pip install .
script:
- python -m unittest discover tests
after_success:
- coverage run -m unittest discover tests
- coveralls
